spring.application.name=demo
spring.datasource.url= jdbc:postgresql://localhost:5432/lpuspring
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.show-sql=false
spring.jpa.open-in-view=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
#enable simple cache- store cache in jvm memeory
#spring.cache.type=simple
server.port=8081


#redis properties
spring.cache.type=redis
spring.redis.host=localhost
spring.redis.port=6379
