spring.application.name=sms


spring.datasource.url= jdbc:postgresql://localhost:5432/sms2
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.show-sql=false
spring.jpa.open-in-view=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
server.port=8082

#enable actuator end point all
management.endpoints.web.exposure.include=*
